<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>d4b78eec-ff78-437d-bd9e-a311d86b1622</UserSecretsId>
    <!-- Sinh file XML để Swagger đọc các thẻ summary. -->
    <GenerateDocumentationFile>true</GenerateDocumentationFile>

    <!-- Không cảnh báo những public member chưa có XML comment. -->
    <NoWarn>$(NoWarn);1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.11">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TuanKietBranchFlow.Application\TuanKietBranchFlow.Application.csproj" />
    <ProjectReference Include="..\TuanKietBranchFlow.Infrastructure\TuanKietBranchFlow.Infrastructure.csproj" />
  </ItemGroup>

</Project>
